version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysqldb
      DB_USERNAME: root
      DB_PASSWORD: khanh123
      DB_DATABASE: money_management
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0.36
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=khanh123
        - MYSQL_DATABASE=money_management 
    ports:
      - 2004:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql

      